version: '3'

services:

  mysql-development:
    image: mysql:8.0.17
    command: --default-authentication-plugin=mysql_native_password
    volumes:
      - mysqldb:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
    ports:
      - "3308:3306"

  admin:
    image: adminer
    ports:
      - "8080:8080"

  backend:
    build: backend
    volumes:
      - backend_public:/usr/src/app/public
    environment:
      TOKEN_SECRET: ${TOKEN_SECRET}
      MYSQL_HOST: "mysql-development"
      MYSQL_PORT: "3306"
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      WAIT_HOSTS: "mysql-development:3306"
      WAIT_HOSTS_TIMEOUT: "120"
            
    ports:
      - "9899:8080"

  frontend:
    build: frontend
    ports:
      - "443:5000"

  backend_public_monitor:
    image: pierrezemb/gostatic
    command: -set-basic-auth ${MONITOR_PWD}
    ports:
      - "9897:8043"
    volumes:
      - backend_public:/srv/http

volumes:
  mysqldb:
  backend_public:
